- name: Install and configure microk8s for all host 
  hosts: all
  tasks:
    - name: Ensure microk8s is installed
      raw: sudo apt update && sudo snap install microk8s --classic \
           microk8s enable dashboard \
           microk8s enable dns \
           microk8s enable registry \
           microk8s enable istio 







