apiVersion: v1
kind: PersistentVolume
metadata:
  name: geoserver-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/geoserver"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
